### ISSUE TITLE
Hyperlinks of testing results are not working

### ISSUE THREAD

**Issue by rockfool** [shangxy7/String-Fortran#1]
Thanks for your sharing.
The links on the examples of testing results fail to display on my web browser.
Could you please confirm and update it?

**Comment by shangxy7** [comment]
Thank you for your valuable suggestions.
The inernal links to each chapter in 'README.md' file, which works well on my laptop, do not work on the web browser, so I have to delink them.
In addition, figures displaying problems are also fixed.
